version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
### Workspace Utilities ##################################
    workspace:
      image: registry.cn-beijing.aliyuncs.com/fanybook/workspace
      volumes:
        - /data/www:/var/www
        - ./workspace/crontab/www-data:/etc/crontabs/www-data
      ports:
        - "2222:22"
      networks:
        - frontend
        - backend


### PHP-FPM ##############################################
    php-fpm:
      image: registry.cn-beijing.aliyuncs.com/fanybook/php-fpm
      volumes:
        - /data/www:/var/www
      depends_on:
        - workspace
      networks:
        - backend


### PHP-Worker ##############################################
#    php-worker:
#      image: registry.cn-beijing.aliyuncs.com/fanybook/php-worker
#      volumes:
#        - /data/www:/var/www
#        - ./logs/pm2:/home/www-data/.pm2/logs
#      ports:
#        - "2223:22"
#      networks:
#        - backend


### Redis ################################################
    redis:
      image: registry.cn-beijing.aliyuncs.com/fanybook/redis
      command: redis-server /etc/redis/redis.conf
      volumes:
        - /data/.mydock/redis:/data
        - ./redis/conf:/etc/redis
      ports:
        - "6379:6379"
      networks:
        - backend


### Caddy Server #########################################
    caddy:
      image: registry.cn-beijing.aliyuncs.com/fanybook/caddy
      volumes:
        - /data/www:/var/www
        - /data/logs/caddy:/var/log/caddy
        - /data/.mydock/caddy:/root/.caddy
        - ./caddy/conf:/etc/caddy
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend


### Certbot ##############################################
    certbot:
      image: fanybook/certbot
      volumes:
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      tty: true
      networks:
        - frontend
